export { Home } from "./Home"
export { Login } from "./Login"
export { ProductsDetail } from "./ProductsDetail"
export { Register } from "./Register"
export { Error } from "./Error"
export { AdminUsersManagement } from "@/components/AdminUsersManagement"
export {ProtectedRoute} from "@/routes/ProtectRoute"
export {UserDashboard }from "@/pages/user/UserDashboard"
export {UserProfile} from "@/pages/user/UserProfile"
export {UserOrders} from "@/pages/user/UserOrders"
export {AdminRoute} from "@/routes/AdminRoute"
export {AdminDashboard} from "@/pages/admins/AdminDashboard"
export {Orders} from "@/pages/admins/Orders"
export { Products } from "@/components/ui/Products"
export { Categories } from "@/components/Categories"